{% set name = "jraph" %}
{% set version = "0.0.6.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jraph-{{ version }}.tar.gz
  sha256: c3ac3a0b224b344eb6d367e8bc312d95ea41bf825d01ea31b80dd8c22c0dd8b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jax >=0.1.55
    - jaxlib >=0.1.37
    - numpy >=1.18.0

test:
  imports:
    - jraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/jraph
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A Graph Neural Network Library in Jax'
  description: |
    Jraph (pronounced "giraffe") is a lightweight library for working with
    graph neural networks in jax. It provides a data structure for graphs,
    a set of utilities for working with graphs, and a 'zoo' of forkable
    graph neural network models.
  doc_url: https://jraph.readthedocs.io/
  dev_url: https://github.com/deepmind/jraph

extra:
  recipe-maintainers:
    - jan-janssen
