{% set name = "jraph" %}
{% set version = "0.0.2.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmind/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 240f092648d0c4d354707ec2f45928840680d5efaed807d69202a1d97c721e3b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jax >=0.1.55
    - jaxlib >=0.1.37
    - numpy >=1.18.0
    - python_version >=0.0.2

test:
  imports:
    - jraph
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/deepmind/jraph
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A Graph Neural Network Library in Jax'
  description: |
    Jraph (pronounced "giraffe") is a lightweight library for working with
    graph neural networks in jax. It provides a data structure for graphs,
    a set of utilities for working with graphs, and a 'zoo' of forkable
    graph neural network models.
  doc_url: https://jraph.readthedocs.io/
  dev_url: https://github.com/deepmind/jraph

extra:
  recipe-maintainers:
    - jan-janssen
